server:
  port: 49816

spring:
  data:
    mongodb:
      database: chat-app
      #      username: dbUser1
      #      password: Nh2XRSbY2C3RWcSo
      uri: mongodb+srv://dbUser1:Nh2XRSbY2C3RWcSo@kabayedb-gw5zw.gcp.mongodb.net/test?retryWrites=true&w=majority